### ISSUE TITLE
Encrypted files supported?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [jhonderson/actual-http-api#1]
Hi,
If the budget file is encrypted, how do I provide the encryption password in the request?

**Comment by jhonderson** [comment]
Not supported as of now. One option I can think of is sending the budget encryption password in some HTTP header, and make use of that password [here](https://github.com/jhonderson/actual-http-api/blob/41fc7fd4be5c914cb1ce79dc04bb2128c707fe09/src/v1/budget.js#L14). I’ll give it a try to that option this or next week.
