### ISSUE TITLE
Support for unofficial syncExternalAccount function to trigger automatic syncs

### ISSUE THREAD

**Issue by ajayjohn** [jhonderson/actual-http-api#11]
Could you please consider adding support for the [syncExternalAccount function described here](https://github.com/actualbudget/actual/issues/2272#issuecomment-1991454717), so that we can trigger automatic syncs for external accounts using your REST API?

**Comment by jhonderson** [comment]
Hello, this project can only use the functionality exposed in the actual nodejs api, meaning it can only use the functions exposed here: https://github.com/actualbudget/actual/blob/master/packages/api/methods.ts

Let me know if there is a function there we can use to trigger the sync.

**Comment by jhonderson** [comment]
Thanks for letting me know. Once Actual release this new `runBankSync` function (upcoming release), I will create an endpoint for it.

**Comment by jhonderson** [comment]
I tried to do this today, but I am getting errors updating, just opened a ticket to Actual: https://github.com/actualbudget/actual/issues/2829

**Comment by jhonderson** [comment]
Added support to trigger bank sync programmatically in [v0.9.0](https://github.com/jhonderson/actual-http-api/releases/tag/v0.9.0).

Thanks all
