### ISSUE TITLE
Missing call for "api/category-groups-get" API endpoint 

### ISSUE THREAD

**Issue by KiPIDesTAN** [jhonderson/actual-http-api#12]
Actual v24.4.0 fixed the missing API call for getCategoryGroups Link to issue - actualbudget/actual#2240 and pull - actualbudget/actual#2446.

The actual-http-api should implement this functionality now that it is available.

Note that I am about to put in a PR that fixes this issue in the actual-http-api. Would you please take a look and merge so this can be shared with others?

**Comment by jhonderson** [comment]
Hello, thanks for your contribution. Of course, I will have a look later today or tomorrow.
