### ISSUE TITLE
Actual budget passwords with special characters not working.

### ISSUE THREAD

**Issue by cgiacofei** [jhonderson/actual-http-api#8]
I was receiving the error:

`Error accessing Actual Server, check Actual Server password Error: Could not get remote files`

Changing my password from `cU9~Qj@BP$jD]4q` (real password that I'm no longer using) to one that was all alphanumeric resolved the issue for me.

I'm using docker compose so not sure if the issue is with the http-api handling the password or compose not escaping characters properly.

For reference this is how the environment was setup in the compose file:
```
    environment:
      - 'ACTUAL_SERVER_URL=https://<SERVER URL>'
      - 'ACTUAL_SERVER_PASSWORD=cU9~Qj@BP$jD]4q'
      - 'API_KEY=<KEY>'
```

**Comment by cgiacofei** [comment]
This has nothing to do with the http-api, docker was interpreting the $jD within the password as a variable.

**Comment by jhonderson** [comment]
Thanks for reporting this, it might be useful for users facing same issue
